### PR TITLE
Fixes for #27

### PR DESCRIPTION
**Pull request by Dr-Terrible**
This PR fixes issue #27 without using symbolic links or other unnecessary hacks. As a bonus, I have added the missing `|| die` after some `rm` / `mv` commands.

I have tested the ebuilds on `no-multilib` and `multilib` profiles, but only for x86_64 archs. I don't have a x86_32 machine for testing. Feedbacks are welcome.

### CODE REVIEW

**Comment by mleise** [comment]
I've tried the fix on x86_32 and the library installs to /opt/dmd-*/lib/ while dmd.conf contains /opt/dmd-*/lib32/, so for example dlang-tools doesn't compile. Also you don't have to change the copyright year for every ebuild. repoman will only complain when actual edits have been made to the file which is more in line with the "publication date" idea of the copyright. The `die` commands were indeed missing, good catch.

Do you want to rework the fix? Otherwise I would pick up your changes and go with the symlink idea.

**Comment by Dr-Terrible** [comment]
> I've tried the fix on x86_32 and the library installs to /opt/dmd-/lib/ while dmd.conf contains /opt/dmd-/lib32/, so for example dlang-tools doesn't compile.

In that case, I'll rework the PR to use $MODEL only on 64bit archs; this way on 32bit machines the library installs to opt/dmd-/lib rather than opt/dmd-/lib32. What do you think of this compromise? Thank you for the feedbacks.

**Comment by mleise** [comment]
That's fine. I just realised that dlang.eclass line 483 contains:
`export LIBDIR_${ABI}="../opt/dmd-${DC_VERSION}/lib${MODEL}"`
This is used by ebuilds that install libraries for DMD, such as GtkD. That line is broken for no-multilib, too. It would also have to be special cased unless the solution is to use lib32/lib64 consistently and never just lib.

**Comment by mleise** [comment]
I decided to close this PR now after a year in limbo and hope that things are working now (and without symlinks)

**Pull request closed without merging**
