### PR TITLE
LDC2 release 0.15.1-r2.

### PR DESCRIPTION
**Pull request by redstar**
This adds support for LLVM 3.6.

### CODE REVIEW

**Comment by mleise** [comment]
Is -fdata-sections -ffunction-section -L--gc-sections automatically active in recent ldc versions?

**Comment by mleise** [comment]
It compiles and runs dub 0.22 and compiles GtkD for me on amd64 using LLVM 3.5.0.

**Comment by mleise** [comment]
How about we mark it ~x86 and ~amd64, test it for about a month and then mark it stable?

**Comment by redstar** [comment]
The goal was to make ldc-0.15.x usable with LLVM 3.6 but there are too many changes required. (Patch set is incomplete.)

**Pull request closed without merging**
