### PR TITLE
Update for ldc 1.0.0 release

### PR DESCRIPTION
**Pull request by Calrama**

### CODE REVIEW

**Comment by mleise** [comment]
Testing it now

**Comment by mleise** [comment]
@Calrama As an extra bonus, if you want you can look into providing an additional "pgo" use flag. PGO during the build process is new in ldc2 1.0.

**Comment by Calrama** [comment]
@mleise I had not heard of PGO before and looking it up lead me to [here](https://wiki.dlang.org/LDC_LLVM_profiling_instrumentation#Profile-Guided_Optimization_.28PGO.29_status_in_LDC), [here](https://github.com/ldc-developers/ldc/pull/1219) and [here](http://johanengelen.github.io/ldc/2016/04/13/PGO-in-LDC-virtual-calls.html), none of which make it clear to me whether it really is in master (and if so, in ldc2 1.0) and if so, whether it is a feature that can be enabled/disabled at compile time of ldc2, or if it is always there and can only be toggled for compiling D code. Without this information readily available I don't see what I could realistically do (OT: Also, most of my free coding time is currently spend working on a proactor socket implementation for libasync, so I don't think I could spare enough of it to do the proper research on the subject).

**Comment by mleise** [comment]
Alright.

**Pull request merged**
