### PR TITLE
add onedrivegui ebuild

### PR DESCRIPTION
**Pull request by MrDuartePT**
This pull request is to add the onedrivegui ebuild.
This ebuild install the package the same way as discord or bitwarden, using the /opt folder.
Also copy a desktop file to the required locationa and create onedrivegui command in /opt/bin to start the app from terminal

### CODE REVIEW

**Comment by MrDuartePT** [comment]
Onedrive-2.4.25 dont need any changes i tested on my machine and work without and problems

**Comment by mleise** [comment]
I guess the D Programming Language overlay is as good as it gets for a GUI to the OneDrive client written in DLang.
If you don't mind, please move it to the category `net-misc` where there is also the Qt5 Nextcloud Desktop Client and change the name to all lowercase. Uppercase is strongly discouraged in the ebuild naming guideline.

**Comment by MrDuartePT** [comment]
I can move it for guru no problem but the only problem it will create a "broken" dependency. 
That why I like to be here. When I get on the laptop again I will make the changes. 
Thank you for your attention.

**Comment by MrDuartePT** [comment]
Do all the change and rebase everthing in one commit

**Comment by MrDuartePT** [comment]
If you add me i dont have problem in mantain this package and also help with onedrive as well because I rely on that package

**Comment by the-horo** [comment]
Something has been lost along the way as onedrivegui-9999.ebuild is what onedrivegui-1.0.2.ebuild should be and onedrivegui-1.0.2.ebuild is a previous iteration of itself.

**Comment by MrDuartePT** [comment]
Yup something get lost. I will fix this later I’m on the laptop right now

**Pull request closed without merging**
