### PR TITLE
Miscellaneous small improvements

### PR DESCRIPTION
**Pull request by MoritzMaxeiner**
Due to the upcoming Funtoo 1.4 natively supporting D 2.076 through GDC's integration in GCC 9 I've soft forked this overlay to [Funtoo's infrastructure](https://code.funtoo.org/bitbucket/users/calrama/repos/dlang-overlay/browse) where that difference'll be reflected.
These are just some quality of life changes I've made that I think upstream would profit from having.

### CODE REVIEW

**Comment by mleise** [comment]
Thank you for the code review. Commit 1 & 2 are good to go, the reason for setting `TARGET_CPU` is to suppress the message `no cpu specified, assuming X86`, which always sounded to me like the package maintainer (i.e. us) are expected to override it. Commit 4 works for dmd, but there are some other packages that require gdmd and so far it was pulled in by the modded GCC ebuilds. We should either always depend on `gdmd` or allow packages to specify whether they need it. Do you think it makes sense to have one gdmd version for each gdc version given how infrequently gdmd is updated? (Not a rethoric question.) Commit 5 seems like the right thing to do. I was just always conservative about making changes to these flags unless someone reports an issue.

**Comment by MoritzMaxeiner** [comment]
Ok, dropping the `TARGET_CPU` commit makes sense, then (done).
Regarding depending on gdmd:
I don't think always depending on gdmd is the way to go; why should dmd depend on gdmd when it's being compiled with e.g. another dmd or ldc2 host compiler? The commit is in line with allowing each package to specify whether they need it: All it does is specify that if you compile dmd with a gdc host compiler, you'll need gdmd.
Concerning the gdmd version: I think that since gdmd is basically just a tighly coupled facade for gdc (and indeed seldom changes itself) that gets installed into the same versioned path as gdc (e.g. `/usr/x86_64-pc-linux-gnu/gcc-bin/9.1.1`) it makes sense to have gdmd mirror the gdc version and bump the patch `-r` suffix when gdmd itself changes. You can see the way I've set this up [here](https://code.funtoo.org/bitbucket/users/calrama/repos/dlang-overlay/browse/dev-util/gdmd/gdmd-9.1.1-r2.ebuild); the primary reason why I didn't include a gdmd update into this PR is that gcc 9 isn't stable on Gentoo yet.
Lastly about adding `-fPIC`: I can report an issue to you, then: Without that, I have to always add `-fPIC` manually to all `dmd` calls on non-multilib amd64 (which has replaced multilib on Funtoo) or face this:
```
echo -n 'void main() {}' | dmd -run - -o-
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: __stdin_3816.o: relocation R_X86_64_32 against symbol `_Dmain' can not be used when making a PIE object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```
```

**Comment by MoritzMaxeiner** [comment]
Also, downstream I'm testing using `/usr/lib` instead of `/opt` for the installation target to be in line with other toolchains/languages (e.g. llvm, python), see [here](https://code.funtoo.org/bitbucket/users/calrama/repos/dlang-overlay/commits/19275eb6d5ad8aa4fae8179efc53333adab8735d#eclass/dlang.eclass). It seems to work well, so far. Is that something you'd be interested having upstreamed?

**Comment by mleise** [comment]
Generally yes, probably with a news item that informs about the path changes. The less effort you have to put into maintaining the extra overlay, the better.

**Pull request merged**
