### PR TITLE
Add ldc2 0.16.0-alpha4.

### PR DESCRIPTION
**Pull request by redstar**
This is the current alpha version of ldc2 plus a patch.

### CODE REVIEW

**Comment by redstar** [comment]
It's a long time since the last ldc2 release. Maybe this is interesting.

**Comment by mleise** [comment]
Sure! I'm already using a 0.16 version from GitHub. Could you add the compiler to eclass/dlang-compilers.eclass? This is so the DLANG_VERSION_RANGE thing in D ebuilds works and provides the correct set of stable/unstable compilers to build a stable/unstable package with.
```
	# LDC
	__dlang_ldc2_frontend_archmap=(
		[1]="2.063 x86 amd64"
		[2]="2.064 x86 amd64"
		[3]="2.065 x86 amd64"
		[4]="2.066 x86 amd64"
		[5]="2.067"  // <- no KEYWORD means "compiler is not marked stable for that KEYWORD"
	)
	__dlang_ldc2_frontend_versionmap=(
		[1]="0.12"
		[2]="0.13"
		[3]="0.14"
		[4]="0.15"
		[5]="0.16"
	)
```

**Comment by redstar** [comment]
I added the eclass, too.

**Comment by mleise** [comment]
LGTM, push the merge button, redstar!

**Pull request merged**
