### PR TITLE
Fix ldc dependencies.

### PR DESCRIPTION
**Pull request by redstar**
- LLVM is compiled as static libraries -> no runtime dependency
- ldc does not work with libconfig-1.5

I don't know if it is correct to change the ebuild or if I need to create a new `-r2` ebuild.

### CODE REVIEW

**Comment by mleise** [comment]
You don't always need a new revision after changes. If practically you would only cause useless rebuilds of the same binaries for those who already have the ebuild merged fine, it is ok to keep the ebuild version the same.
Is that a correct way to specify a version range? I would probably have written "=dev-libs/libconfig-1.4*", not knowing if >= && < is according to the specs.

**Comment by redstar** [comment]
Oh, you are right about the range dependency: https://devmanual.gentoo.org/general-concepts/dependencies/#ranged-dependencies. I change this.

**Comment by redstar** [comment]
Seems to be possible: have a look at https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sys-cluster/neutron/neutron-2015.1.9999.ebuild?view=markup line 29ff

"=dev-libs/libconfig-1.4*" is not equal to ">=dev-libs/libconfig-1.4.7" and "<dev-libs/libconfig-1.5" as it also allows version 1.4.5.
Therefore I reverted my change.

**Comment by mleise** [comment]
And it really doesn't depend on LLVM at runtime!

**Pull request merged**
