### PR TITLE
Fixes gentoo/dlang#96

### PR DESCRIPTION
**Pull request by AlexandreFournier**
x11-terms/tilix: use autoconf:1.16

### CODE REVIEW

**Comment by mleise** [comment]
Thank you, can you add `--signoff` to your commit command line? Otherwise I can't push it to Gentoo's Git. I forgot to mention that in the README when the switch was made.

**Comment by AlexandreFournier** [comment]
I think it's done

**Comment by mleise** [comment]
Excellent.
grafik

**Comment by mleise** [comment]
Is that your actual email? The expected email was "pro" at your domain.

**Comment by AlexandreFournier** [comment]
I have many emails, me@ is the one i use on github.

**Comment by mleise** [comment]
Unfortunately Gentoo (where I push the commits to) remembers you as pro@ and rejects your commits:
```
remote: 1a8b1d1efa3e7c0db8ce472c201fc4702626b784: no Signed-off-by line matching committer's e-mail address found!
remote:   expected: pro@<domain removed by me>
remote:   last found: me@<domain removed by me>
remote: 
remote: Please make sure to read the copyright policy before adding Signed-off-by!
remote:   https://www.gentoo.org/glep/glep-0076.html
remote: error: hook declined to update refs/heads/master
```

**Comment by AlexandreFournier** [comment]
Fixed

**Pull request merged**
