### PR TITLE
Version bumps for ldc2 and dub

### PR DESCRIPTION
**Pull request by Calrama**
One thing to note, though:
Since c605e11eab4e1d9dfe84c586f19b07b3eedc5746 I have to apply the following patch to build dub:

```
diff --git a/eclass/dlang.eclass b/eclass/dlang.eclass
index 67d0c6c..6b74f6f 100644
--- a/eclass/dlang.eclass
+++ b/eclass/dlang.eclass
@@ -268,7 +268,7 @@ declare -a __dlang_depends
 
 __dlang_compiler_masked_archs_for_version_range() {
        local iuse=$1
-       local depend="!ppc-aix? ( !ppc64-linux? ( !ppc-macos? ( !ppc-openbsd? ( $iuse? ( $2 ) ) ) ) )"
+       local depend="!ppc-aix? ( !ppc64-linux? ( !ppc-macos? ( $iuse? ( $2 ) ) ) )"
        local dlang_version=${3%% *}
        local compiler_keywords=${3:${#dlang_version}}
        local compiler_keyword package_keyword nomatch anyworks usable arch have_one
```

Otherwise, `ebuild` errors out about `ppc-openbsd` not being in `IUSE`. Could be a Funtoo issue, I'm not sure, though.

### CODE REVIEW

**Comment by ff2000** [comment]
Same thing on std. Gentoo regarding ppc-openbsd. Fix would be very appreciated :)

**Comment by Calrama** [comment]
This ppc-openbsd use flag is also why repoman is unhappy in the CI check.
I'd include the patch in this PR if I understood why these use flags where even added in the first place and what other consequences removing them might have.

**Comment by edgar444** [comment]
Don't know how to read ebuilds, but deleting that part allows me to finally build dmd version i need. (Because of library features that I wan't to use.)

So until then dmd-2.072.2 wont compile. :/

```
Blackout-MicroSD ~ # emerge -av '=dmd-2.072.2'
These are the packages that would be merged, in order:
Calculating dependencies... done!
!!! All ebuilds that could satisfy "=dmd-2.072.2" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-lang/dmd-2.072.2::dlang (masked by: invalid: DEPEND: USE flag 'ppc-openbsd' referenced in conditional '!ppc-openbsd?' is not in IUSE, invalid: RDEPEND: USE flag 'ppc-openbsd' referenced in conditional '!ppc-openbsd?' is not in IUSE)
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

**Comment by edgar444** [comment]
March 30, dlang repo still broke... having to manually remove `ppc-openbsd` from eclass file.

```
localhost ~ # emerge -avq '=dmd-2.071.2'

!!! All ebuilds that could satisfy "=dmd-2.071.2" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-lang/dmd-2.071.2::dlang (masked by: invalid: DEPEND: USE flag 'ppc-openbsd' referenced in conditional '!ppc-openbsd?' is not in IUSE, invalid: RDEPEND: USE flag 'ppc-openbsd' referenced in conditional '!ppc-openbsd?' is not in IUSE)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

**Comment by Calrama** [comment]
Yeah, I'm currently torn between waiting longer for @mleise and just using my own fork from now on. In the meantime I'm using the pre-compiled versions of dmd and ldc, but that's no real solution.

**Comment by mleise** [comment]
Looks good, @Calrama. But we have a problem with the LLVM support provided by Gentoo. After [this commit](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5fd038c745f0e79973ac475bd46be0a7fc8b7426) there is only x86/amd64/arm left, and no ppc or sparc, so we need to drop these options from LDC as well or the dependency wont be resolved. GCC seems to be the only option for these architectures for now.

**Comment by Calrama** [comment]
@mleise Thanks for the info; due to me not having a working Linux box for the next ~2 weeks, though, I won't be able to help with that soon.

**Pull request merged**
